### PR TITLE
Add a new and better way for fetching transaction details

### PR DESCRIPTION
**Pull request by iAkashPattnaik**
- Implemented fetching transaction details via `tx_ref`
- Updated docs

### CODE REVIEW

**Comment by iAkashPattnaik** [comment]
* I must say, this is a much better implementation than [flutterwave](https://developer.flutterwave.com/docs/sdks-and-plugins/backend-libraries)'s official [rave-python](https://github.com/Flutterwave/Python-v2) implementation. [rave-python](https://github.com/Flutterwave/Python-v2) is pure shit with the worst docs I've ever seem!

**Review by WilliamOtieno — APPROVED** [review]
LGTM

**Comment by WilliamOtieno** [comment]
Yep, the major reason why I started working on this lib

**Comment by WilliamOtieno** [comment]
Anyway, it’s been a while since I maintained the package. I’ll go back to flutterwave docs and see what’s new so that we update the lib with new features.

**Pull request merged**
